export const tagOptions = [
    {key: 1, text: 'mmorpg', value: 'mmorpg'},
    {key: 2, text: 'shooter', value: 'shooter'},
    {key: 3, text: 'strategy', value: 'strategy'},
    {key: 4, text: 'moba', value: 'moba'},
    {key: 5, text: 'racing', value: 'racing'},
    {key: 6, text: 'sports', value: 'sports'},
    {key: 7, text: 'social', value: 'social'},
    {key: 8, text: 'sandbox', value: 'sandbox'},
    {key: 9, text: 'open-world', value: 'open-world'},
    {key: 10, text: 'survival', value: 'survival'},
    {key: 11, text: 'pvp', value: 'pvp'},
    {key: 12, text: 'pve', value: 'pve'},
    {key: 13, text: 'pixel', value: 'pixel'},
    {key: 14, text: 'voxel', value: 'voxel'},
    {key: 15, text: 'zombie', value: 'zombie'},
    {key: 16, text: 'turn-based', value: 'turn-based'},
    {key: 17, text: 'first-person', value: 'first-person'},
    {key: 18, text: 'third-person', value: 'third-person'},
    {key: 19, text: 'top-down', value: 'top-down'},
    {key: 20, text: 'tank', value: 'tank'},
    {key: 21, text: 'space', value: 'space'},
    {key: 22, text: 'sailing', value: 'sailing'},
    {key: 23, text: 'side-scroller', value: 'side-scroller'},
    {key: 24, text: 'superhero', value: 'superhero'},
    {key: 25, text: 'permadeath', value: 'permadeath'},
    {key: 26, text: 'card', value: 'card'},
    {key: 27, text: 'battle-royale', value: 'battle-royale'},
    {key: 28, text: 'mmo', value: 'mmo'},
    {key: 29, text: 'mmofps', value: 'mmofps'},
    {key: 30, text: 'action', value: 'action'},
    {key: 31, text: 'military', value: 'military'},
    {key: 32, text: 'martial-arts', value: 'martial-arts'},
    {key: 33, text: 'low-spec', value: 'low-spec'},
    {key: 34, text: 'tower-defense', value: 'tower-defense'},
    {key: 35, text: 'horror', value: 'horror'},
    {key: 36, text: 'mmorts', value: 'mmorts'},
  ]

export const platformOptions = [
    {key: 1, text: 'all', value: 'all'},
    {key: 2, text: 'pc', value: 'pc'},
    {key: 3, text: 'browser', value: 'browser'},
]

export const sortOptions = [
    {key: 1, text: 'Дата публикации', value: 'release-date'},
    {key: 2, text: 'Популярность', value: 'popularity'},
    {key: 3, text: 'По алфавиту ', value: 'alphabetical '},
    {key: 4, text: 'Акстивности ', value: 'relevance '},
]